/* ISO-8859-14 (latin8) Celtic charmap
 * Alastair McKinstry <amck@maths.tcd.ie>
 */

char *iso_8859_14_syms[]={
    "nobreakspace",		/* AO  */
    "Bdotabove",
    "bdotabove",
    "sterling",
    "Cdotabove",
    "cdotabove",
    "Ddotabove",
    "section",
    "Wgrave",
    "copyright",
    "Wacute",
    "ddotabove",
    "Ygrave",
    "soft_hyphen",
    "registered",
    "Ydiaeresis",
    "Fdotabove",		/* BO */
    "fdotabove",
    "Gdotabove",
    "gdotabove",
    "Mdotabove",
    "mdotabove",
    "pilcrow",
    "Pdotabove",
    "wgrave",
    "pdotabove",
    "wacute",
    "Sdotabove",
    "ygrave",
    "Wdiaeresis",
    "wdiaeresis",
    "sdotabove",
    "Agrave",			/* C0 */
    "Aacute",
    "Acircumflex",
    "Atilde",
    "Adiaeresis",
    "Aring",
    "AE",
    "Ccedilla",
    "Egrave",
    "Eacute",
    "Ecircumflex",
    "Ediaeresis",
    "Igrave",
    "Iacute",
    "Icircumflex",
    "Idiaeresis",
    "Wcircumflex",		/* D0 */
    "Ntilde",
    "Ograve",
    "Ocircumflex",
    "Odiaeresis",
    "Tdotabove",
    "Oslash",
    "Ugrave",
    "Uacute",
    "Ucircumflex",
    "Udiaeresis",
    "Yacute",
    "Ycircumflex",
    "ssharp",
    "agrave",			/* E0 */
    "aacute",
    "acircumflex",
    "atilde",
    "adiaeresis",
    "aring",
    "ae",
    "ccedilla",
    "egrave",
    "eacute",
    "ecircumflex",
    "ediaeresis",
    "igrave",
    "iacute",
    "icircumflex",
    "idiaeresis",
    "wcircumflex",		/* F0 */
    "ntilde",
    "ograve",
    "oacute",
    "ocircumflex",
    "otilde",
    "odiaeresis",
    "tdotabove",
    "ostroke",
    "ugrave",
    "uacute",
    "ucircumflex",
    "udiaeresis",
    "yacute",
    "ycircumflex",
    "ydiaeresis"
};

	
    
