#!/bin/bash

# $Debian: cvs/debian/postrm,v 1.1 2001/04/20 16:00:54 epg Exp $

if [ "$1" = "remove" -a -x /usr/sbin/update-inetd ]; then
	update-inetd --remove "^cvspserver"
fi
if [ "$1" = "purge" ]; then
	. /usr/share/debconf/confmodule
	db_purge
	rm -f /etc/cvs.conf
fi
# Automatically added by dh_installdebconf
if [ "$1" = purge -a -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

