#!/bin/sh -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/fortune-mod -a -d /usr/share/doc/fortune-mod ]; then
		ln -sf ../share/doc/fortune-mod /usr/doc/fortune-mod
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ "$1" = "configure" -a -x /usr/bin/update-menus ]; then update-menus ; fi
# End automatically added section
