#!/bin/sh -e
# $Id: postinst,v 1.1 2000/03/23 10:27:08 herbert Exp $

update-alternatives --install /usr/bin/ftp ftp /usr/bin/netkit-ftp 100 \
		    --slave /usr/share/man/man1/ftp.1.gz ftp.1.gz \
		    	    /usr/share/man/man1/netkit-ftp.1.gz

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/ftp -a -d /usr/share/doc/ftp ]; then
		ln -sf ../share/doc/ftp /usr/doc/ftp
	fi
fi
# End automatically added section

