#!/bin/sh -e

if [ "$1" != "upgrade" ]; then
  update-alternatives --remove infobrowser /usr/bin/info
fi

if [ "$1" = "remove" -o "$1" = "upgrade" ]; then
  install-info --remove --quiet /usr/share/info/info-stnd.info
  install-info --remove --quiet /usr/share/info/info.info
fi

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/info ]; then
	rm -f /usr/doc/info
fi
# End automatically added section

