#!/bin/sh -e

if [ "$1" = "upgrade" ]; then
	# save portmap state; will be reread when portmap start is run
	pmap_dump >/var/run/portmap.upgrade-state
fi

## Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/portmap ]; then
	rm -f /usr/doc/portmap
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -e "/etc/init.d/portmap" ]; then
	/etc/init.d/portmap stop
fi
# End automatically added section
#
