#!/bin/sh

if [ "$1" != "upgrade" ]
then
	update-alternatives --remove w /usr/bin/w.procps
fi

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/procps ]; then
	rm -f /usr/doc/procps
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -e "/etc/init.d/procps.sh" ]; then
	/etc/init.d/procps.sh stop
fi
# End automatically added section


exit 0

