/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */
#define __stub_chflags
#define __stub_fattach
#define __stub_fchflags
#define __stub_fdetach
#define __stub_feclearexcept
#define __stub_fedisableexcept
#define __stub_feenableexcept
#define __stub_fegetenv
#define __stub_fegetexcept
#define __stub_fegetexceptflag
#define __stub_fegetround
#define __stub_feholdexcept
#define __stub_feraiseexcept
#define __stub_fesetenv
#define __stub_fesetexceptflag
#define __stub_fesetround
#define __stub_fetestexcept
#define __stub_feupdateenv
#define __stub_fexecve
#define __stub_getcontext
#define __stub_getmsg
#define __stub_getpmsg
#define __stub_gtty
#define __stub_makecontext
#define __stub_posix_fadvise
#define __stub_posix_fadvise64
#define __stub_putmsg
#define __stub_putpmsg
#define __stub_revoke
#define __stub_setcontext
#define __stub_setlogin
#define __stub_sigreturn
#define __stub_sstk
#define __stub_stty
#define __stub_swapcontext
